# Generated by Django 5.0 on 2024-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakansi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
