# Generated by Django 5.0 on 2024-11-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_vakansi_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakansi',
            name='photo',
            field=models.ImageField(upload_to='media/v_photos'),
        ),
    ]
