# Generated by Django 5.0 on 2024-11-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_request_created_at_alter_request_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakansi',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
