# Generated by Django 5.0 on 2024-11-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_vakansi_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakansi',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/v_photos'),
        ),
    ]
